/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Controlador.TLista_Auto;
import Controlador.TLista_Moto;
import Entidades.Auto;
import Entidades.Moto;
import Entidades.Vehiculo;
import java.awt.Panel;
import javax.swing.JOptionPane;
import javax.swing.RootPaneContainer;

/**
 *
 * @author maldo
 */
public class EditVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form SISTEMA_VEHICULO
     */
    public EditVehiculo() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1______INGRESAR______ = new javax.swing.JButton();
        jButton1______IMPRIMIR______ = new javax.swing.JButton();
        jButton1______IMPRIMIR_AUTO______ = new javax.swing.JButton();
        jButton2______IMPRIMIR_MOTO______ = new javax.swing.JButton();
        jButton1______CANCELAR______ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("SISTEMA DE VEHÍCULO");

        jLabel2.setText("TIPO DE VEHÍCULO: ");

        jLabel3.setText("MODELO: ");

        jLabel4.setText("MARCA: ");

        jLabel5.setText("NÚMERO DE PUERTAS: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AUTO", "MOTO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1______INGRESAR______.setText("INGRESAR");
        jButton1______INGRESAR______.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1______INGRESAR______ActionPerformed(evt);
            }
        });

        jButton1______IMPRIMIR______.setText("IMPRIMIR");
        jButton1______IMPRIMIR______.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1______IMPRIMIR______ActionPerformed(evt);
            }
        });

        jButton1______IMPRIMIR_AUTO______.setText("AUTO");
        jButton1______IMPRIMIR_AUTO______.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1______IMPRIMIR_AUTO______ActionPerformed(evt);
            }
        });

        jButton2______IMPRIMIR_MOTO______.setText("MOTO");
        jButton2______IMPRIMIR_MOTO______.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2______IMPRIMIR_MOTO______ActionPerformed(evt);
            }
        });

        jButton1______CANCELAR______.setText("CANCELAR");
        jButton1______CANCELAR______.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1______CANCELAR______ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jButton1______IMPRIMIR______))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                            .addComponent(jTextField2)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jButton1______INGRESAR______)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1______CANCELAR______)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1______IMPRIMIR_AUTO______)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2______IMPRIMIR_MOTO______))
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1______INGRESAR______)
                    .addComponent(jButton1______IMPRIMIR_AUTO______)
                    .addComponent(jButton2______IMPRIMIR_MOTO______))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1______IMPRIMIR______)
                    .addComponent(jButton1______CANCELAR______))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Auto au;
    Moto mo;

    private void jButton1______INGRESAR______ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1______INGRESAR______ActionPerformed
        // TODO add your handling code here:

        if (jComboBox1.getSelectedItem().equals("AUTO")) {
            String marca = jTextField1.getText();
            String modelo = jTextField2.getText();
            int numPuertas = Integer.parseInt(jTextField3.getText());
            
            au = new Auto(numPuertas, marca, modelo);
            TLista_Auto.Insertar(au);
            AdminVehiculo.Cargar_Datos();
            
        }
        
        if (jComboBox1.getSelectedItem().equals("MOTO")) {
            String marca = jTextField1.getText();
            String modelo = jTextField2.getText();
            double cilindraje = Double.parseDouble(jTextField3.getText());
            
            mo = new Moto(cilindraje, marca, modelo);
            TLista_Moto.Insertar_Moto(mo);
            AdminVehiculo.Cargar_Datos();
            
        }

    }//GEN-LAST:event_jButton1______INGRESAR______ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().equals("MOTO")) {
            jLabel5.setText("CILINDRAJE");
        } else {
            if (jComboBox1.getSelectedItem().equals("AUTO")) {
                jLabel5.setText("NÚMERO DE PUERTAS");
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1______IMPRIMIR_AUTO______ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1______IMPRIMIR_AUTO______ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, au.Imprimir_Auto());

    }//GEN-LAST:event_jButton1______IMPRIMIR_AUTO______ActionPerformed

    private void jButton2______IMPRIMIR_MOTO______ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2______IMPRIMIR_MOTO______ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, mo.Imprimir_Moto());

    }//GEN-LAST:event_jButton2______IMPRIMIR_MOTO______ActionPerformed

    private void jButton1______IMPRIMIR______ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1______IMPRIMIR______ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, au.Imprimir_Auto() + "\n" + mo.Imprimir_Moto());

    }//GEN-LAST:event_jButton1______IMPRIMIR______ActionPerformed

    private void jButton1______CANCELAR______ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1______CANCELAR______ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_jButton1______CANCELAR______ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1______CANCELAR______;
    private javax.swing.JButton jButton1______IMPRIMIR_AUTO______;
    private javax.swing.JButton jButton1______IMPRIMIR______;
    private javax.swing.JButton jButton1______INGRESAR______;
    private javax.swing.JButton jButton2______IMPRIMIR_MOTO______;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
